version: '3'
services:
  db:
    container_name: apollowithmysql
    image: mysql:5.7.27
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./.data/db:/var/lib/mysql
      - ./.data/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inu
      MYSQL_USER: test
      MYSQL_PASSWORD: test
